### PR TITLE
Namespace separation ala packages

### PR DESCRIPTION
**Pull request by guicho271828**

### CODE REVIEW

**Comment by guicho271828** [comment]
oh, I found it is broken. Examples do not run.

**Comment by guicho271828** [comment]
Huge renaming ongoing...
+ Remove kernel manager
+ follow the opencl terminology. The *kernel* mentioned in the library is actually a *program*.

**Comment by guicho271828** [comment]
All examples work. Summary:

+ Kernel manager has been removed
+ `defkernel` expands into a kernel instantiation
+ `kernel` class is renamed into `program` class
+ Introduced `define-program`, `in-program`, `use-program` etc.

```lisp
(define-program :diffuse0-eazyopencl
  (:use :oclcl)) ;; <- default program containing let*, when macros etc.
(in-program :diffuse0-eazyopencl)
```

+ Future work (will not be added in this round of commit): Adding import, shadow, shadowning import

**Review by gos-k — APPROVED** [review]

**Comment by gos-k** [comment]
LGTM
Thunks!

**Pull request merged**
