### PR TITLE
Compiler directive

### PR DESCRIPTION
**Pull request by guicho271828**

### CODE REVIEW

**Comment by gos-k** [comment]
@guicho271828 please revert a8447f0853c5dfcb1bece783a9e58ce593f9bba1
ci failure maybe dirty cache

**Comment by guicho271828** [comment]
It builds on my account. How does that happen???
https://travis-ci.org/guicho271828/oclcl/jobs/290468988

**Comment by guicho271828** [comment]
could you clear the cache and rebuild the PR on your side?

**Comment by gos-k** [comment]
ci success.
LGTM
thx

**Comment by guicho271828** [comment]
thanks

**Pull request merged**
